package com.example.model.IO.errors;


public enum Errors {
    NO_ERROR,
    INVALID_COMMAND,
    USER_ALREADY_EXISTS,
    INVALID_USERNAME_FORMAT,
    INVALID_PASSWORD,
    REGISTER_SUCCESSFUL,
    USER_DOESNT_EXIST,
    PASSWORD_DOESNT_MATCH,
    LOGIN_SUCCESSFUL,
    NO_ACCOUNT_TO_LOGOUT,
    INVALID_USERNAME,
    WEAK_PASSWORD,
    INVALID_EMAIL,
    WRONG_ANSWER_CONFIRMATION,
    PASSWORD_CHANGED,
    REGISTER_FIRST_STEP_SUCCESSFUL,
    SET_PASSWORD,
    WRONG_SECURITY_QUESTION,
    USERNAME_CHANGED,
    INVALID_NICKNAME,
    NICKNAME_CHANGED,
    EMAIL_CHANGED,
    PASSWORD_IS_SAME,
    SPECIAL_CARD_ERROR, NOT_ENOUGH_CARDS, DONT_HAVE_PLAYED_GAME, YOU_CANT_PLAY_WITH_YOURSELF;
}
