package com.example.model.IO.errors;


public enum LoginMenuErrors {
    NO_ERROR,
    INVALID_COMMAND,
    USER_ALREADY_EXISTS,
    INVALID_USERNAME_FORMAT,
    INVALID_PASSWORD,
    REGISTER_SUCCESSFUL,
    USER_DOESNT_EXIST,
    PASSWORD_DOESNT_MATCH,
    LOGIN_SUCCESSFUL,
    NO_ACCOUNT_TO_LOGOUT,
    INVALID_USERNAME, WEAK_PASSWORD, INVALID_EMAIL, WRONG_ANSWER_CONFIRMATION, PASSWORD_CHANGED, REGISTER_FIRST_STEP_SUCCESSFUL, SET_PASSWORD;
}
